### ISSUE TITLE
How many epochs to train tanda in your experiments?

### ISSUE THREAD

**Issue by zhiqiangdon** [HazyResearch/tanda#13]
Hi,

Thanks for your code. How many epochs do you train tanda on MNIST and Cifar respectively? I couldn't find the details in your paper. In your demo script, you set the epoch=1. Is one epoch enough?

Thanks,

**Comment by henryre** [comment]
Hi @zhiqiangdon, yes we found that training the TAN for a single epoch was sufficient for MNIST and CIFAR-10.

**Comment by zhiqiangdon** [comment]
Thanks for your reply!
