### ISSUE TITLE
offline transformation using pretrained model

### ISSUE THREAD

**Issue by af3113** [HazyResearch/tanda#14]
Hi, 
I have trained a tanda model and I would like to use it to generate several transformations of my dataset and save it to disk. Is there any exemplar script which can give me some hints how to do that?
Many thanks

**Comment by henryre** [comment]
Hi @af3113, sorry for the late response. Check out https://github.com/HazyResearch/tanda/blob/master/keras/utils.py for an example of loading in a pretrained TAN. From there, you can loop over your original data and call `TAN.transform(...)`, saving the output to disk.
