### ISSUE TITLE
Question regarding the usage of batch_norm 

### ISSUE THREAD

**Issue by amirkhojaste** [HazyResearch/tanda#18]
Hey guys, 

Thanks again for open sourcing your codes. It is really an interesting work. I had a quick question regarding the way batch_norm is applied in your code.

In the tanda/discreminator/discremintor.py :: build_supervised function, there is these lines of code:

#Note: In order to save batch_norm moving averages--which are needed
#at test time--need to save them in a collection (see README) with
#name self.bn_vars_collection, o/w won't get saved!
vars_list += tf.get_collection_ref(self.bn_vars_collection)

I have read both your (tanda/discreminator/README) file regarding the usage of tf.contrib.layers.batch_norm function as well as the tensorflow docs. I don't see why we should add the variables to the list here. Since we are using "tf.control_dependencies" on the optimization part, we are making sure the "moving_mean" and "moving_variance" of batch_norm function are getting updated so in the inference time, we should be OK. I actually have printed the moving_mean/vars of some of the layers in both train and inference time and they seem to be updated.

Is it still necessary to do this addition??

In fact, the end model training code **fails** here with the following error:

**ValueError: At least two variables have the same name: D/unit_1_0/shared_activation/init_bn/beta**

It fails at the next line, i.e: 

self.saver = tf.train.Saver(var_list=vars_list)

I am using tensorflow 1.9.0 and Python 2.

**Comment by ajratner** [comment]
Hi @amirkhojaste thanks for flagging this issue!

I believe this is a TensorFlow version issue (we were using TF 1.2); we will at very least change the python requirements file to this effect in the short run.

As for upgrading to support TF 1.9- I'm not sure how quickly we'll be able to get to this, but will put on the list- and if you find a quick fix, please feel free to throw up a PR!

Thanks!
Alex

**Comment by henryre** [comment]
Closing with #19
